---
deployment:
  tasks:
    - export DEPLOYPATH=/home/justinz1/public_html/test/
    - /bin/cp -R src $DEPLOYPATH
    - /bin/cp index.js $DEPLOYPATH
    - /bin/cp package-lock.json $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH